import dotenv from "dotenv";
import mongoose from "mongoose";
import bcrypt from "bcryptjs";
import { User } from "../models/user.model.js";
import { Company } from "../models/company.model.js";
import { Job } from "../models/job.model.js";

dotenv.config();

const seededRecruiter = {
  fullname: "Seed Recruiter",
  email: "seed.recruiter@jobportal.dev",
  phoneNumber: "9999999999",
  password: "Seed@12345",
  role: "recruiter",
};

const seededCompany = {
  name: "Seeded Tech Labs",
  description:
    "Sample company generated by job seeder for local development and demos.",
  website: "https://seeded-tech-labs.example",
  location: "Bengaluru, India",
  logo: "",
};

const jobs = [
  {
    title: "Frontend React Developer",
    description:
      "Build responsive user interfaces with React, Redux Toolkit, and Tailwind CSS.",
    requirements: ["React", "Redux Toolkit", "JavaScript", "Tailwind CSS"],
    salary: 12,
    experienceLevel: 2,
    location: "Bengaluru",
    jobType: "Full-time",
    position: "Frontend Engineer",
  },
  {
    title: "Backend Node.js Developer",
    description:
      "Design and maintain secure REST APIs with Express and MongoDB.",
    requirements: ["Node.js", "Express", "MongoDB", "JWT"],
    salary: 14,
    experienceLevel: 3,
    location: "Hyderabad",
    jobType: "Full-time",
    position: "Backend Engineer",
  },
  {
    title: "Full Stack MERN Developer",
    description:
      "Own features end-to-end across React frontend and Node.js backend services.",
    requirements: ["MongoDB", "Express", "React", "Node.js"],
    salary: 16,
    experienceLevel: 4,
    location: "Pune",
    jobType: "Contract",
    position: "Full Stack Engineer",
  },
  {
    title: "UI Developer Intern",
    description:
      "Support the frontend team by building reusable components and clean layouts.",
    requirements: ["HTML", "CSS", "React basics", "Git"],
    salary: 4,
    experienceLevel: 0,
    location: "Remote",
    jobType: "Internship",
    position: "Frontend Intern",
  },
  {
    title: "QA Automation Engineer",
    description:
      "Implement test automation for web applications and API workflows.",
    requirements: ["Cypress", "Playwright", "JavaScript", "REST API testing"],
    salary: 10,
    experienceLevel: 2,
    location: "Chennai",
    jobType: "Full-time",
    position: "QA Engineer",
  },
  {
    title: "DevOps Engineer",
    description:
      "Maintain CI/CD pipelines and cloud deployment flows for production services.",
    requirements: ["Docker", "CI/CD", "Linux", "Cloud basics"],
    salary: 15,
    experienceLevel: 3,
    location: "Mumbai",
    jobType: "Full-time",
    position: "DevOps Engineer",
  },
];

const seedJobs = async () => {
  const mongoUri = process.env.MONGO_URI;
  if (!mongoUri) {
    throw new Error("MONGO_URI is missing in backend/.env");
  }

  await mongoose.connect(mongoUri);
  console.log("MongoDB connected for seeding");

  let recruiter = await User.findOne({ email: seededRecruiter.email });
  if (!recruiter) {
    const hashedPassword = await bcrypt.hash(seededRecruiter.password, 10);
    recruiter = await User.create({
      ...seededRecruiter,
      password: hashedPassword,
    });
    console.log(`Created recruiter: ${recruiter.email}`);
  } else {
    console.log(`Using existing recruiter: ${recruiter.email}`);
  }

  let company = await Company.findOne({ name: seededCompany.name });
  if (!company) {
    company = await Company.create({
      ...seededCompany,
      userId: recruiter._id,
    });
    console.log(`Created company: ${company.name}`);
  } else {
    company.userId = recruiter._id;
    company.description = seededCompany.description;
    company.website = seededCompany.website;
    company.location = seededCompany.location;
    company.logo = seededCompany.logo;
    await company.save();
    console.log(`Updated company: ${company.name}`);
  }

  let upsertedCount = 0;
  for (const job of jobs) {
    const result = await Job.updateOne(
      { title: job.title, company: company._id },
      {
        $set: {
          ...job,
          company: company._id,
          created_by: recruiter._id,
        },
      },
      { upsert: true }
    );

    if (result.upsertedCount > 0 || result.modifiedCount > 0) {
      upsertedCount += 1;
    }
  }

  const totalCompanyJobs = await Job.countDocuments({ company: company._id });
  console.log(`Jobs inserted/updated in this run: ${upsertedCount}`);
  console.log(`Total jobs for ${company.name}: ${totalCompanyJobs}`);
  console.log(
    `Recruiter login -> email: ${seededRecruiter.email}, password: ${seededRecruiter.password}`
  );
};

seedJobs()
  .then(async () => {
    await mongoose.disconnect();
    console.log("Seeding complete");
  })
  .catch(async (error) => {
    console.error("Seeding failed:", error.message);
    await mongoose.disconnect();
    process.exit(1);
  });
